### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [BudSystemLimited/Cake.DocumentDb#2]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by jonathanstowell** [comment]
I'll try and have a look at this next time I do some work on the project. I think the team are close to starting to use this package themselves now so it maybe we end up doing this as a company over a period of time.

Otherwise I'll try and get some time over the next month or so to start on this.

**Comment by gep13** [comment]
@jonathanstowell that is great news, thanks for getting back to me!

**Comment by gep13** [comment]
@jonathanstowell I am going to close this off, as adding yml files to the website is now an automated process via the Cake.AddinDiscoverer tool that has been developed.
